{{- if and .Values.rbac.enabled (not .Values.rbac.namespaced) -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "microservice-text-chat.fullname" . }}-clusterrolebinding
  labels:
    {{- include "microservice-text-chat.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "microservice-text-chat.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "microservice-text-chat.serviceAccountName" . }}
    namespace: {{ template "microservice-text-chat.namespace" . }}
{{- end -}}
